version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile-apache
    container_name: sf4apache
    ports:
      - 80:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/sf4
    depends_on:
      - node

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: sf4php
    volumes:
      - .:/home/wwwroot/sf4
    depends_on:
      - apache

  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    container_name: nodefe
    ports:
      - 4200:4200
      - 9876:9876
    volumes:
      - ./nodefe:/app
